name: Build

on:
  push:
    branches:
      - dev
      - master
      - release-*
      - 1.*
  pull_request:
    branches:
      - dev
      - master
      - release-*
      - 1.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Build and tests
        run: ./mvnw -B clean verify -Pe2e,integration-test

#      - name: Send message to Slack channel
#        if: ${{ failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master') }}
#        uses: ./.github/actions/notify-slack
#        with:
#          CHANNEL_ID: ${{ secrets.SLACK_UID_CHANNEL_ID }}
#          MESSAGE: ":x: Build on branch ${{github.ref}} failed in bonita portal look and feel."
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}