name: Release bonita-portal-look-and-feel

on:
  workflow_dispatch:
    inputs:
      version:
        description: new version to release
        required: true

jobs:
  createGithubRelease:
    name: Create release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure Maven Settings
        uses: bonitasoft/maven-settings-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Configure Git user
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}

      - name: Build Release
        run: ./mvnw --batch-mode release:prepare -DreleaseVersion=${{ github.event.inputs.version }}

      - name: Publish
        run: mvn --batch-mode release:perform

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          generateReleaseNotes: true
